spring:
  datasource:
    url: jdbc:h2:mem:test
    username: test
    password:
    driverClassName: org.h2.Driver

  jpa:
    show-sql: true
    hibernate.ddl-auto: create

  shell:
    interactive:
      enabled: false

  h2:
    console:
      enabled: true
      path: /h2-console

  data:
    rest:
      base-path: /api

app:
  security:
    remember-me-key: Remember-Me-Key
